define(function(){

    'use strict';

    /* Generated by SHJS CSS to Theme converter.
     * Theme Name: vampire
     * Converted at: Tue Jul 03 2012 14:16:17 GMT-0400 (EDT)
     * Converted from: sh_vampire.css
     */

    var theme = {
        "default": {
            "background-color": "#000000",
            "color": "#ff0000",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "keyword": {
            "color": "#ffffff",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "type": {
            "color": "#F35E1E",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "string": {
            "color": "#bb00ff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "regexp": {
            "color": "#bb00ff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "specialchar": {
            "color": "#ffffff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "comment": {
            "color": "#ababab",
            "font-weight": "normal",
            "font-style": "italic"
        },
        "number": {
            "color": "#bb00ff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "preproc": {
            "color": "#ababab",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "symbol": {
            "color": "#F3E651",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "function": {
            "color": "#7bc710",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "cbracket": {
            "color": "#F3E651",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "url": {
            "color": "#bb00ff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "date": {
            "color": "#ffffff",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "time": {
            "color": "#ffffff",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "file": {
            "color": "#ffffff",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "ip": {
            "color": "#bb00ff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "name": {
            "color": "#bb00ff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "variable": {
            "color": "#ffffff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "oldfile": {
            "color": "#ffffff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "newfile": {
            "color": "#bb00ff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "difflines": {
            "color": "#ffffff",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "selector": {
            "color": "#ffffff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "property": {
            "color": "#ffffff",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "value": {
            "color": "#bb00ff",
            "font-weight": "normal",
            "font-style": "normal"
        }
    };

    return {
        theme: theme
    };
});