define(function(){

    'use strict';

    /* Generated by SHJS CSS to Theme converter.
     * Theme Name: berries-dark
     * Converted at: Tue Jul 03 2012 14:16:17 GMT-0400 (EDT)
     * Converted from: sh_berries-dark.css
     */

    var theme = {
        "default": {
            "background-color": "#80bfff",
            "color": "#400080",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "keyword": {
            "color": "#3f2bf0",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "type": {
            "color": "#3f2bf0",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "string": {
            "color": "#c40000",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "regexp": {
            "color": "#c40000",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "specialchar": {
            "color": "#77379a",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "comment": {
            "color": "#df0959",
            "font-weight": "normal",
            "font-style": "italic"
        },
        "number": {
            "color": "#20755a",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "preproc": {
            "color": "#0628cb",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "symbol": {
            "color": "#000000",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "function": {
            "color": "#901164",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "cbracket": {
            "color": "#000000",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "url": {
            "color": "#c40000",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "date": {
            "color": "#3f2bf0",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "time": {
            "color": "#3f2bf0",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "file": {
            "color": "#3f2bf0",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "ip": {
            "color": "#c40000",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "name": {
            "color": "#c40000",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "variable": {
            "color": "#a91ea7",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "oldfile": {
            "color": "#77379a",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "newfile": {
            "color": "#c40000",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "difflines": {
            "color": "#3f2bf0",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "selector": {
            "color": "#a91ea7",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "property": {
            "color": "#3f2bf0",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "value": {
            "color": "#c40000",
            "font-weight": "normal",
            "font-style": "normal"
        }
    };

    return {
        theme: theme
    };
});