define(function(){

    'use strict';

    /* Generated by SHJS CSS to Theme converter.
     * Theme Name: bipolar
     * Converted at: Tue Jul 03 2012 14:16:17 GMT-0400 (EDT)
     * Converted from: sh_bipolar.css
     */

    var theme = {
        "default": {
            "background-color": "#000000",
            "color": "#d149a6",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "keyword": {
            "color": "#ee85e2",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "type": {
            "color": "#aadd8b",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "string": {
            "color": "#9ef457",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "regexp": {
            "color": "#9ef457",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "specialchar": {
            "color": "#9ef457",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "comment": {
            "color": "#35d6e5",
            "font-weight": "normal",
            "font-style": "italic"
        },
        "number": {
            "color": "#ffffff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "preproc": {
            "color": "#07f6bf",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "symbol": {
            "color": "#348fef",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "function": {
            "color": "#d51993",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "cbracket": {
            "color": "#348fef",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "url": {
            "color": "#9ef457",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "date": {
            "color": "#ee85e2",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "time": {
            "color": "#ee85e2",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "file": {
            "color": "#ee85e2",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "ip": {
            "color": "#9ef457",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "name": {
            "color": "#9ef457",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "variable": {
            "color": "#72d42c",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "oldfile": {
            "color": "#9ef457",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "newfile": {
            "color": "#9ef457",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "difflines": {
            "color": "#ee85e2",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "selector": {
            "color": "#72d42c",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "property": {
            "color": "#ee85e2",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "value": {
            "color": "#9ef457",
            "font-weight": "normal",
            "font-style": "normal"
        }
    };

    return {
        theme: theme
    };
});