define(function(){

    'use strict';

    /* Generated by SHJS CSS to Theme converter.
     * Theme Name: easter
     * Converted at: Tue Jul 03 2012 14:16:17 GMT-0400 (EDT)
     * Converted from: sh_easter.css
     */

    var theme = {
        "default": {
            "background-color": "#ffff80",
            "color": "#2C7B34",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "keyword": {
            "color": "#1d45d6",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "type": {
            "color": "#ed0f55",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "string": {
            "color": "#ca4be3",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "regexp": {
            "color": "#ca4be3",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "specialchar": {
            "color": "#ca4be3",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "comment": {
            "color": "#24c815",
            "font-weight": "normal",
            "font-style": "italic"
        },
        "number": {
            "color": "#e11a70",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "preproc": {
            "color": "#1583b1",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "symbol": {
            "color": "#fa4700",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "function": {
            "color": "#1d45d6",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "cbracket": {
            "color": "#fa4700",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "url": {
            "color": "#ca4be3",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "date": {
            "color": "#1d45d6",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "time": {
            "color": "#1d45d6",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "file": {
            "color": "#1d45d6",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "ip": {
            "color": "#ca4be3",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "name": {
            "color": "#ca4be3",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "variable": {
            "color": "#26aae7",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "oldfile": {
            "color": "#ca4be3",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "newfile": {
            "color": "#ca4be3",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "difflines": {
            "color": "#1d45d6",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "selector": {
            "color": "#26aae7",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "property": {
            "color": "#1d45d6",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "value": {
            "color": "#ca4be3",
            "font-weight": "normal",
            "font-style": "normal"
        }
    };

    return {
        theme: theme
    };
});