define(function(){

    'use strict';

    /* Generated by SHJS CSS to Theme converter.
     * Theme Name: bright
     * Converted at: Tue Jul 03 2012 14:16:17 GMT-0400 (EDT)
     * Converted from: sh_bright.css
     */

    var theme = {
        "default": {
            "background-color": "#ffffff",
            "color": "#401e7a",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "keyword": {
            "color": "#ff3030",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "type": {
            "color": "#f7b92c",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "string": {
            "color": "#1861a7",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "regexp": {
            "color": "#1861a7",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "specialchar": {
            "color": "#1861a7",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "comment": {
            "color": "#38ad24",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "number": {
            "color": "#32ba06",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "preproc": {
            "color": "#5374b0",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "symbol": {
            "color": "#3030ee",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "function": {
            "color": "#d11ced",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "cbracket": {
            "color": "#3030ee",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "url": {
            "color": "#1861a7",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "date": {
            "color": "#ff3030",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "time": {
            "color": "#ff3030",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "file": {
            "color": "#ff3030",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "ip": {
            "color": "#1861a7",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "name": {
            "color": "#1861a7",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "variable": {
            "color": "#0000ff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "oldfile": {
            "color": "#1861a7",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "newfile": {
            "color": "#1861a7",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "difflines": {
            "color": "#ff3030",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "selector": {
            "color": "#0000ff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "property": {
            "color": "#ff3030",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "value": {
            "color": "#1861a7",
            "font-weight": "normal",
            "font-style": "normal"
        }
    };

    return {
        theme: theme
    };
});
