define(function(){

    'use strict';

    /* Generated by SHJS CSS to Theme converter.
     * Theme Name: peachpuff
     * Converted at: Tue Jul 03 2012 14:16:17 GMT-0400 (EDT)
     * Converted from: sh_peachpuff.css
     */

    var theme = {
        "default": {
            "background-color": "#ffdab9",
            "color": "#000000",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "keyword": {
            "color": "#a52a2a",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "type": {
            "color": "#2e8b57",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "string": {
            "color": "#c00058",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "regexp": {
            "color": "#c00058",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "specialchar": {
            "color": "#6a5acd",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "comment": {
            "color": "#406090",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "number": {
            "color": "#c00058",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "preproc": {
            "color": "#cd00cd",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "function": {
            "color": "#521cc7",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "url": {
            "color": "#c00058",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "date": {
            "color": "#a52a2a",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "time": {
            "color": "#a52a2a",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "file": {
            "color": "#a52a2a",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "ip": {
            "color": "#c00058",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "name": {
            "color": "#c00058",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "variable": {
            "color": "#275fec",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "oldfile": {
            "color": "#6a5acd",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "newfile": {
            "color": "#c00058",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "difflines": {
            "color": "#a52a2a",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "selector": {
            "color": "#275fec",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "property": {
            "color": "#a52a2a",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "value": {
            "color": "#c00058",
            "font-weight": "normal",
            "font-style": "normal"
        }
    };

    return {
        theme: theme
    };
});