define(function(){

    'use strict';

    /* Generated by SHJS CSS to Theme converter.
     * Theme Name: rand01
     * Converted at: Tue Jul 03 2012 14:16:17 GMT-0400 (EDT)
     * Converted from: sh_rand01.css
     */

    var theme = {
        "default": {
            "background-color": "#ffffff",
            "color": "#121b28",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "keyword": {
            "color": "#0a7f6d",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "type": {
            "color": "#c42638",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "string": {
            "color": "#2b83ba",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "regexp": {
            "color": "#2b83ba",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "specialchar": {
            "color": "#a764cb",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "comment": {
            "color": "#ababab",
            "font-weight": "normal",
            "font-style": "italic"
        },
        "number": {
            "color": "#0da344",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "preproc": {
            "color": "#620ac6",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "symbol": {
            "color": "#0000de",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "function": {
            "color": "#000000",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "cbracket": {
            "color": "#0000de",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "url": {
            "color": "#2b83ba",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "date": {
            "color": "#0a7f6d",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "time": {
            "color": "#0a7f6d",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "file": {
            "color": "#0a7f6d",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "ip": {
            "color": "#2b83ba",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "name": {
            "color": "#2b83ba",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "variable": {
            "color": "#e12f76",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "oldfile": {
            "color": "#a764cb",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "newfile": {
            "color": "#2b83ba",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "difflines": {
            "color": "#0a7f6d",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "selector": {
            "color": "#e12f76",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "property": {
            "color": "#0a7f6d",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "value": {
            "color": "#2b83ba",
            "font-weight": "normal",
            "font-style": "normal"
        }
    };

    return {
        theme: theme
    };
});