define(function(){

    'use strict';

    /* Generated by SHJS CSS to Theme converter.
     * Theme Name: blacknblue
     * Converted at: Tue Jul 03 2012 14:16:17 GMT-0400 (EDT)
     * Converted from: sh_blacknblue.css
     */

    var theme = {
        "default": {
            "background-color": "#000000",
            "color": "#2346d5",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "keyword": {
            "color": "#1ededc",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "type": {
            "color": "#c06cf8",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "string": {
            "color": "#cfc631",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "regexp": {
            "color": "#cfc631",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "specialchar": {
            "color": "#ccc6c6",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "comment": {
            "color": "#6fb2c4",
            "font-weight": "normal",
            "font-style": "italic"
        },
        "number": {
            "color": "#c4ac60",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "preproc": {
            "color": "#8080ff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "symbol": {
            "color": "#ccc6c6",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "function": {
            "color": "#1c96ed",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "cbracket": {
            "color": "#ccc6c6",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "url": {
            "color": "#cfc631",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "date": {
            "color": "#1ededc",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "time": {
            "color": "#1ededc",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "file": {
            "color": "#1ededc",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "ip": {
            "color": "#cfc631",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "name": {
            "color": "#cfc631",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "variable": {
            "color": "#ecea26",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "oldfile": {
            "color": "#ccc6c6",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "newfile": {
            "color": "#cfc631",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "difflines": {
            "color": "#1ededc",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "selector": {
            "color": "#ecea26",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "property": {
            "color": "#1ededc",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "value": {
            "color": "#cfc631",
            "font-weight": "normal",
            "font-style": "normal"
        }
    };

    return {
        theme: theme
    };
});