define(function(){

    'use strict';

    /* Generated by SHJS CSS to Theme converter.
     * Theme Name: desert
     * Converted at: Tue Jul 03 2012 14:16:17 GMT-0400 (EDT)
     * Converted from: sh_desert.css
     */

    var theme = {
        "default": {
            "background-color": "#af947e",
            "color": "#fffdec",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "keyword": {
            "color": "#fef8bc",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "type": {
            "color": "#fef8bc",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "string": {
            "color": "#f6f647",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "regexp": {
            "color": "#f6f647",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "specialchar": {
            "color": "#f6f647",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "comment": {
            "color": "#a00000",
            "font-weight": "normal",
            "font-style": "italic"
        },
        "number": {
            "color": "#3e3f25",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "preproc": {
            "color": "#833914",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "symbol": {
            "color": "#66574f",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "function": {
            "color": "#f3d266",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "cbracket": {
            "color": "#66574f",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "url": {
            "color": "#f6f647",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "date": {
            "color": "#fef8bc",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "time": {
            "color": "#fef8bc",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "file": {
            "color": "#fef8bc",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "ip": {
            "color": "#f6f647",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "name": {
            "color": "#f6f647",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "variable": {
            "color": "#000000",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "oldfile": {
            "color": "#f6f647",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "newfile": {
            "color": "#f6f647",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "difflines": {
            "color": "#fef8bc",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "selector": {
            "color": "#000000",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "property": {
            "color": "#fef8bc",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "value": {
            "color": "#f6f647",
            "font-weight": "normal",
            "font-style": "normal"
        }
    };

    return {
        theme: theme
    };
});