define(function(){

    'use strict';

    /* Generated by SHJS CSS to Theme converter.
     * Theme Name: greenlcd
     * Converted at: Tue Jul 03 2012 14:16:17 GMT-0400 (EDT)
     * Converted from: sh_greenlcd.css
     */

    var theme = {
        "default": {
            "background-color": "#003400",
            "color": "#00bb00",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "keyword": {
            "color": "#00ed00",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "type": {
            "color": "#00ed00",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "string": {
            "color": "#dfdfdf",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "regexp": {
            "color": "#dfdfdf",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "specialchar": {
            "color": "#dfdfdf",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "comment": {
            "color": "#888888",
            "font-weight": "normal",
            "font-style": "italic"
        },
        "number": {
            "color": "#ffffff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "preproc": {
            "color": "#bfbfbf",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "symbol": {
            "color": "#2fe7a9",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "function": {
            "color": "#c0ff73",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "cbracket": {
            "color": "#2fe7a9",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "url": {
            "color": "#dfdfdf",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "date": {
            "color": "#00ed00",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "time": {
            "color": "#00ed00",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "file": {
            "color": "#00ed00",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "ip": {
            "color": "#dfdfdf",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "name": {
            "color": "#dfdfdf",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "variable": {
            "color": "#beef13",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "oldfile": {
            "color": "#dfdfdf",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "newfile": {
            "color": "#dfdfdf",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "difflines": {
            "color": "#00ed00",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "selector": {
            "color": "#beef13",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "property": {
            "color": "#00ed00",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "value": {
            "color": "#dfdfdf",
            "font-weight": "normal",
            "font-style": "normal"
        }
    };

    return {
        theme: theme
    };
});