define(function(){

    'use strict';

    /* Generated by SHJS CSS to Theme converter.
     * Theme Name: dull
     * Converted at: Tue Jul 03 2012 14:16:17 GMT-0400 (EDT)
     * Converted from: sh_dull.css
     */

    var theme = {
        "default": {
            "background-color": "#bfbfbf",
            "color": "#656565",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "keyword": {
            "color": "#353535",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "type": {
            "color": "#3241c6",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "string": {
            "color": "#005599",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "regexp": {
            "color": "#005599",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "specialchar": {
            "color": "#005599",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "comment": {
            "color": "#d11d20",
            "font-weight": "normal",
            "font-style": "italic"
        },
        "number": {
            "color": "#16930d",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "preproc": {
            "color": "#000033",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "symbol": {
            "color": "#222222",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "function": {
            "color": "#38255c",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "cbracket": {
            "color": "#222222",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "url": {
            "color": "#005599",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "date": {
            "color": "#353535",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "time": {
            "color": "#353535",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "file": {
            "color": "#353535",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "ip": {
            "color": "#005599",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "name": {
            "color": "#005599",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "variable": {
            "color": "#ae5a16",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "oldfile": {
            "color": "#005599",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "newfile": {
            "color": "#005599",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "difflines": {
            "color": "#353535",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "selector": {
            "color": "#ae5a16",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "property": {
            "color": "#353535",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "value": {
            "color": "#005599",
            "font-weight": "normal",
            "font-style": "normal"
        }
    };

    return {
        theme: theme
    };
});