define(function(){

    'use strict';

    /* Generated by SHJS CSS to Theme converter.
     * Theme Name: navy
     * Converted at: Tue Jul 03 2012 14:16:17 GMT-0400 (EDT)
     * Converted from: sh_navy.css
     */

    var theme = {
        "default": {
            "background-color": "#000035",
            "color": "#008bff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "keyword": {
            "color": "#f8c50b",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "type": {
            "color": "#e1e72f",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "string": {
            "color": "#ffffff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "regexp": {
            "color": "#ffffff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "specialchar": {
            "color": "#ffffff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "comment": {
            "color": "#ffbb00",
            "font-weight": "normal",
            "font-style": "italic"
        },
        "number": {
            "color": "#f87ff4",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "preproc": {
            "color": "#bb00ff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "symbol": {
            "color": "#ffffff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "function": {
            "color": "#ffffff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "cbracket": {
            "color": "#ffffff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "url": {
            "color": "#ffffff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "date": {
            "color": "#f8c50b",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "time": {
            "color": "#f8c50b",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "file": {
            "color": "#f8c50b",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "ip": {
            "color": "#ffffff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "name": {
            "color": "#ffffff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "variable": {
            "color": "#13d8ef",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "oldfile": {
            "color": "#ffffff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "newfile": {
            "color": "#ffffff",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "difflines": {
            "color": "#f8c50b",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "selector": {
            "color": "#13d8ef",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "property": {
            "color": "#f8c50b",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "value": {
            "color": "#ffffff",
            "font-weight": "normal",
            "font-style": "normal"
        }
    };

    return {
        theme: theme
    };
});