define(function(){

    'use strict';

    /* Generated by SHJS CSS to Theme converter.
     * Theme Name: berries-light
     * Converted at: Tue Jul 03 2012 14:16:17 GMT-0400 (EDT)
     * Converted from: sh_berries-light.css
     */

    var theme = {
        "default": {
            "background-color": "#d7ffff",
            "color": "#47406d",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "keyword": {
            "color": "#2cae1e",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "type": {
            "color": "#8b51c0",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "string": {
            "color": "#5f81b3",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "regexp": {
            "color": "#5f81b3",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "specialchar": {
            "color": "#5f81b3",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "comment": {
            "color": "#9c3caf",
            "font-weight": "normal",
            "font-style": "italic"
        },
        "number": {
            "color": "#20755a",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "preproc": {
            "color": "#0628cb",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "symbol": {
            "color": "#d2073b",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "function": {
            "color": "#901164",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "cbracket": {
            "color": "#d2073b",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "url": {
            "color": "#5f81b3",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "date": {
            "color": "#2cae1e",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "time": {
            "color": "#2cae1e",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "file": {
            "color": "#2cae1e",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "ip": {
            "color": "#5f81b3",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "name": {
            "color": "#5f81b3",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "variable": {
            "color": "#0628cb",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "oldfile": {
            "color": "#5f81b3",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "newfile": {
            "color": "#5f81b3",
            "font-weight": "normal",
            "font-style": "normal"
        },
        "difflines": {
            "color": "#2cae1e",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "selector": {
            "color": "#0628cb",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "property": {
            "color": "#2cae1e",
            "font-weight": "bold",
            "font-style": "normal"
        },
        "value": {
            "color": "#5f81b3",
            "font-weight": "normal",
            "font-style": "normal"
        }
    };

    return {
        theme: theme
    };
});